name: Build and deploy frontend

on:
  push:
    branches:
      - develop
    paths:
      - src/frontend/**
      - .github/workflows/build-deploy-frontend.yml

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: src/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "./src/frontend/build/*"
          target: "/var/www/midterm.somesandwich.rocks/html"
          rm: true

      - name: Remove all old file
        uses: appleboy/ssh-action@v1.0.0
        with:
          script_stop: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Move all file to root folder
            mv /var/www/midterm.somesandwich.rocks/html/src/build/* /var/www/midterm.somesandwich.rocks/html
            rm -rf /var/www/midterm.somesandwich.rocks/html/src
